version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres-17.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/docker/postgres/shared:/home
      - ${HOME}/docker/postgres/17.2/data:/var/lib/postgresql/data
    restart: unless-stopped
